---
- hosts: master
  gather_facts: false
  
  tasks:
    - name: Generate a k8s token 
      command: python -c 'import random; print "%0x.%0x" % (random.SystemRandom().getrandbits(3*8), random.SystemRandom().getrandbits(8*8))'
      register: token
    - debug: var=token.stdout

- hosts: minions
  become: true
  vars_files:
    - group_vars/vars.yml
  strategy: free
  remote_user: arista

  tasks:
    - name: Add swap space
      command: echo 'Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"' >> /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      
    - name: Add the Google signing key
      apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present

    - name: Add the k8s APT repo
      apt_repository: repo='deb http://apt.kubernetes.io/ kubernetes-xenial main' state=present

    - name: Install packages
      apt: name={{ item }} state=installed update_cache=true force=yes
      with_items: "{{ PACKAGES }}"

    - name: Copy the static hosts file
      copy:
          src: /etc/hosts
          dest: /etc/hosts

    - name: Join the k8s cluster with the appropriate token
      command: kubeadm join --token {{ hostvars['10.1.1.02']['token']['stdout'] }}  {{ master_ip }}:6443


